### PR TITLE
example tts add param tts_rule_fsts

### PR DESCRIPTION
**Pull request by ghjdegithub**

### CODE REVIEW

**Comment by thewh1teagle** [comment]
@ghjdegithub 

Please enable the option to allow edit the pull request.

**Comment by ghjdegithub** [comment]
> @ghjdegithub
> 
> Please enable the option to allow edit the pull request.

image
It's always on.

**Comment by thewh1teagle** [comment]
@ghjdegithub 

```console
➜  sherpa-rs git:(ghjdegithub/main) git push                                                
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 1023 bytes | 1023.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/ghjdegithub/sherpa-rs.git
 ! [remote rejected] ghjdegithub/main -> ghjdegithub/main (permission denied)
error: failed to push some refs to 'https://github.com/ghjdegithub/sherpa-rs.git'
```

I can't push to it. It works in other pull requests / repositories the same way.

**Comment by ghjdegithub** [comment]
I invited you.
https://github.com/ghjdegithub/sherpa-rs/invitations

**Comment by thewh1teagle** [comment]
@ghjdegithub 

I think I understand why I can't push to this PR/your branch. It seems the PR was created from your main branch, which is protected. In the future, it might be better to create PRs from a separate branch instead of the main branch.

**Comment by ghjdegithub** [comment]
> @ghjdegithub 
> 
> 
> 
> I think I understand why I can't push to this PR/your branch. It seems the PR was created from your main branch, which is protected. In the future, it might be better to create PRs from a separate branch instead of the main branch.

Consider creating a dev branch

**Comment by thewh1teagle** [comment]
Looks good now. Thanks!

**Pull request merged**
