### PR TITLE
Submit streaming code and examples

### PR DESCRIPTION
**Pull request by ghjdegithub**

### CODE REVIEW

**Comment by thewh1teagle** [comment]
@ghjdegithub 

Although it's direct bindings to sherpa when it's possible I prefer to simplify the interface to sherpa onnx while it's possible to keep the flexibility. Hope that make sense.
Also see the review comments

**Comment by ghjdegithub** [comment]
> @ghjdegithub 
> 
> 
> 
> Although it's direct bindings to sherpa when it's possible I prefer to simplify the interface to sherpa onnx even more while it's possible to keep the flexibility. Hope that make sense.
> 
> Also see the review comments 
> 
> 
> 
> Also try to keep only critical comments. Users should work alongside sherpa onnx docs so we don't need to maintain them

The first step is to wrap sherpa's unsafe code in a rust-safe structure, which is also safe to expose, and then that safe structure in again wrapping this higher level structure that you're talking about. And then it will continue to encapsulate a little bit more structure like your ziptransform.

**Comment by thewh1teagle** [comment]
@ghjdegithub 

Please create another PR with same changes not from your main branch. I can't edit PR's that comes from main branch of others.

**Comment by thewh1teagle** [comment]
> The first step is to wrap sherpa's unsafe code in a rust-safe structure, which is also safe to expose, and then that safe structure in again wrapping this higher level structure that you're talking about. And then it will continue to encapsulate a little bit more structure like your ziptransform.



> The first step is to wrap sherpa's unsafe code in a rust-safe structure, which is also safe to expose, and then that safe structure in again wrapping this higher level structure that you're talking about. And then it will continue to encapsulate a little bit more structure like your ziptransform.

Can you describe it in pseudo code? What's the benefits over the current approach given the fact that the codebase is small currently?

**Comment by ghjdegithub** [comment]
> > The first step is to wrap sherpa's unsafe code in a rust-safe structure, which is also safe to expose, and then that safe structure in again wrapping this higher level structure that you're talking about. And then it will continue to encapsulate a little bit more structure like your ziptransform.
> 
> > The first step is to wrap sherpa's unsafe code in a rust-safe structure, which is also safe to expose, and then that safe structure in again wrapping this higher level structure that you're talking about. And then it will continue to encapsulate a little bit more structure like your ziptransform.
> 
> Can you describe it in pseudo code? What's the benefits over the current approach given the fact that the codebase is small currently?

First, higher-level encapsulation relies only on secure rust code. Second, the rust structure that continues to be encapsulated by unsafe code can provide maximum extensibility to the outside world. You can see that my onlinestream has made a special encapsulation, which can call one function after the caller, but the other function cannot be called, and this operation is prohibited directly in the compilation layer, without documentation.

**Comment by ghjdegithub** [comment]
@thewh1teagle 
It's best not to rely on high-level abstractions on unsafe code, which is very rusty. For example, your zipformer directly depends on the unsafe code, which is very unsafe and rusty.

**Pull request closed without merging**
